main: me.theguyhere.villagerdefense.Main
name: VillagerDefense
version: 1.0.2
author: Theguyhere
api-version: 1.16
depend: [HolographicDisplays]
softdepend: [WorldGuard, WorldEdit, Multiverse-core]

commands:
  vd:
    admin:
      description: Opens up the admin panel for Villager Defense
      usage: /vd admin
      permission: vd.use
    help:
      description: Redirects players to the Villager Defense wiki
      usage: /vd help
    leave:
      description: Removes players from arenas and teleports them to the lobby
      usage: /vd leave
    stats:
      description: Displays stats of a player
      usage: /vd stats
    kits:
      description: Displays kits of the player
      usage: /vd kits
    join:
      description: Attempt to join a full arena with the phantom kit.
      usage: /vd join
    crystals:
      description: Changes the crystal balance of players
      usage: /vd crystals
      permission: vd.crystals
    start:
      description: Forces the start of a game
      usage: /vd start
      permission: vd.start
    end:
      description: Forces the end of a game
      usage: /vd end
      permission: vd.admin
    delay:
      description: Forces a game to restart its waiting time
      usage: /vd delay
      permission: vd.start
    fix:
      description: Tries to automatically update files
      usage: /vd fix
      permission: vd.admin
    debug:
      description: Changes the plugin debug level
      usage: /vd debug
      permission: vd.admin
    die:
      description: Kills the player that initiates the command, if they are in an active game as an active player
      usage: /vd die